/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SuprimentosRouteImport } from './routes/suprimentos'
import { Route as SolicitacoesMaterialRouteImport } from './routes/solicitacoes-material'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PosvendaRouteImport } from './routes/posvenda'
import { Route as PedidosVendaRouteImport } from './routes/pedidos-venda'
import { Route as PaineisRouteImport } from './routes/paineis'
import { Route as OperacoesFinanceirasRouteImport } from './routes/operacoes-financeiras'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FinanciamentosRouteImport } from './routes/financiamentos'
import { Route as FinanceiroTitulosRouteImport } from './routes/financeiro-titulos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueFundacaoRouteImport } from './routes/estoque-fundacao'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EngenhariaRouteImport } from './routes/engenharia'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AssinaturasRouteImport } from './routes/assinaturas'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnalisesRouteImport } from './routes/analises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaineisSplatRouteImport } from './routes/paineis.$'
import { Route as DashboardsPosvendaRouteImport } from './routes/dashboards.posvenda'
import { Route as DashboardsFinanciamentosRouteImport } from './routes/dashboards.financiamentos'
import { Route as DashboardsFinanceiroRouteImport } from './routes/dashboards.financeiro'
import { Route as DashboardsEstoqueRouteImport } from './routes/dashboards.estoque'
import { Route as DashboardsEngenhariaRouteImport } from './routes/dashboards.engenharia'
import { Route as DashboardsComercialRouteImport } from './routes/dashboards.comercial'
import { Route as DashboardsAprovacoesRouteImport } from './routes/dashboards.aprovacoes'
import { Route as ConfiguracoesTestesCargaRouteImport } from './routes/configuracoes.testes-carga'
import { Route as ConfiguracoesContabilRouteImport } from './routes/configuracoes.contabil'
import { Route as AnalyticsSaudeSistemaRouteImport } from './routes/analytics.saude-sistema'
import { Route as AnalyticsSaudeDadosRouteImport } from './routes/analytics.saude-dados'
import { Route as AnalyticsPosvendaRouteImport } from './routes/analytics.posvenda'
import { Route as AnalyticsPerformanceRouteImport } from './routes/analytics.performance'
import { Route as AnalyticsGovernancaRouteImport } from './routes/analytics.governanca'
import { Route as AnalyticsFinanciamentosRouteImport } from './routes/analytics.financiamentos'
import { Route as AnalyticsFinanceiroRouteImport } from './routes/analytics.financeiro'
import { Route as AnalyticsEstoqueRouteImport } from './routes/analytics.estoque'
import { Route as AnalyticsErrosRouteImport } from './routes/analytics.erros'
import { Route as AnalyticsEngenhariaRouteImport } from './routes/analytics.engenharia'
import { Route as AnalyticsComercialRouteImport } from './routes/analytics.comercial'
import { Route as AnalyticsAprovacoesRouteImport } from './routes/analytics.aprovacoes'
import { Route as EngenhariaGestaoServicosIndexRouteImport } from './routes/engenharia.gestao-servicos.index'
import { Route as ComercialContratosIndexRouteImport } from './routes/comercial.contratos.index'
import { Route as ComercialClientesIndexRouteImport } from './routes/comercial.clientes.index'
import { Route as EngenhariaGestaoServicosModelosRouteImport } from './routes/engenharia.gestao-servicos.modelos'
import { Route as EngenhariaGestaoServicosOsIdRouteImport } from './routes/engenharia.gestao-servicos.$osId'
import { Route as ComercialProjetosProjetoIdRouteImport } from './routes/comercial.projetos.$projetoId'
import { Route as ComercialContratosContratoIdRouteImport } from './routes/comercial.contratos.$contratoId'
import { Route as ComercialClientesBackfillRouteImport } from './routes/comercial.clientes.backfill'
import { Route as ComercialClientesClienteIdRouteImport } from './routes/comercial.clientes.$clienteId'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuprimentosRoute = SuprimentosRouteImport.update({
  id: '/suprimentos',
  path: '/suprimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesMaterialRoute = SolicitacoesMaterialRouteImport.update({
  id: '/solicitacoes-material',
  path: '/solicitacoes-material',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PosvendaRoute = PosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosVendaRoute = PedidosVendaRouteImport.update({
  id: '/pedidos-venda',
  path: '/pedidos-venda',
  getParentRoute: () => rootRouteImport,
} as any)
const PaineisRoute = PaineisRouteImport.update({
  id: '/paineis',
  path: '/paineis',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesFinanceirasRoute = OperacoesFinanceirasRouteImport.update({
  id: '/operacoes-financeiras',
  path: '/operacoes-financeiras',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentosRoute = FinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroTitulosRoute = FinanceiroTitulosRouteImport.update({
  id: '/financeiro-titulos',
  path: '/financeiro-titulos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueFundacaoRoute = EstoqueFundacaoRouteImport.update({
  id: '/estoque-fundacao',
  path: '/estoque-fundacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRoute = EngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesRoute = AnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaineisSplatRoute = PaineisSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PaineisRoute,
} as any)
const DashboardsPosvendaRoute = DashboardsPosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsFinanciamentosRoute =
  DashboardsFinanciamentosRouteImport.update({
    id: '/financiamentos',
    path: '/financiamentos',
    getParentRoute: () => DashboardsRoute,
  } as any)
const DashboardsFinanceiroRoute = DashboardsFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsEstoqueRoute = DashboardsEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsEngenhariaRoute = DashboardsEngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsComercialRoute = DashboardsComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsAprovacoesRoute = DashboardsAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => DashboardsRoute,
} as any)
const ConfiguracoesTestesCargaRoute =
  ConfiguracoesTestesCargaRouteImport.update({
    id: '/testes-carga',
    path: '/testes-carga',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesContabilRoute = ConfiguracoesContabilRouteImport.update({
  id: '/contabil',
  path: '/contabil',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const AnalyticsSaudeSistemaRoute = AnalyticsSaudeSistemaRouteImport.update({
  id: '/saude-sistema',
  path: '/saude-sistema',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsSaudeDadosRoute = AnalyticsSaudeDadosRouteImport.update({
  id: '/saude-dados',
  path: '/saude-dados',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsPosvendaRoute = AnalyticsPosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsPerformanceRoute = AnalyticsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsGovernancaRoute = AnalyticsGovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsFinanciamentosRoute = AnalyticsFinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsFinanceiroRoute = AnalyticsFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsEstoqueRoute = AnalyticsEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsErrosRoute = AnalyticsErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsEngenhariaRoute = AnalyticsEngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsComercialRoute = AnalyticsComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsAprovacoesRoute = AnalyticsAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AnalyticsRoute,
} as any)
const EngenhariaGestaoServicosIndexRoute =
  EngenhariaGestaoServicosIndexRouteImport.update({
    id: '/gestao-servicos/',
    path: '/gestao-servicos/',
    getParentRoute: () => EngenhariaRoute,
  } as any)
const ComercialContratosIndexRoute = ComercialContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialClientesIndexRoute = ComercialClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => ComercialRoute,
} as any)
const EngenhariaGestaoServicosModelosRoute =
  EngenhariaGestaoServicosModelosRouteImport.update({
    id: '/gestao-servicos/modelos',
    path: '/gestao-servicos/modelos',
    getParentRoute: () => EngenhariaRoute,
  } as any)
const EngenhariaGestaoServicosOsIdRoute =
  EngenhariaGestaoServicosOsIdRouteImport.update({
    id: '/gestao-servicos/$osId',
    path: '/gestao-servicos/$osId',
    getParentRoute: () => EngenhariaRoute,
  } as any)
const ComercialProjetosProjetoIdRoute =
  ComercialProjetosProjetoIdRouteImport.update({
    id: '/projetos/$projetoId',
    path: '/projetos/$projetoId',
    getParentRoute: () => ComercialRoute,
  } as any)
const ComercialContratosContratoIdRoute =
  ComercialContratosContratoIdRouteImport.update({
    id: '/contratos/$contratoId',
    path: '/contratos/$contratoId',
    getParentRoute: () => ComercialRoute,
  } as any)
const ComercialClientesBackfillRoute =
  ComercialClientesBackfillRouteImport.update({
    id: '/clientes/backfill',
    path: '/clientes/backfill',
    getParentRoute: () => ComercialRoute,
  } as any)
const ComercialClientesClienteIdRoute =
  ComercialClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => ComercialRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/assinaturas': typeof AssinaturasRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/fornecedores': typeof FornecedoresRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/operacoes-financeiras': typeof OperacoesFinanceirasRoute
  '/paineis': typeof PaineisRouteWithChildren
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacoes-material': typeof SolicitacoesMaterialRoute
  '/suprimentos': typeof SuprimentosRoute
  '/tarefas': typeof TarefasRoute
  '/analytics/aprovacoes': typeof AnalyticsAprovacoesRoute
  '/analytics/comercial': typeof AnalyticsComercialRoute
  '/analytics/engenharia': typeof AnalyticsEngenhariaRoute
  '/analytics/erros': typeof AnalyticsErrosRoute
  '/analytics/estoque': typeof AnalyticsEstoqueRoute
  '/analytics/financeiro': typeof AnalyticsFinanceiroRoute
  '/analytics/financiamentos': typeof AnalyticsFinanciamentosRoute
  '/analytics/governanca': typeof AnalyticsGovernancaRoute
  '/analytics/performance': typeof AnalyticsPerformanceRoute
  '/analytics/posvenda': typeof AnalyticsPosvendaRoute
  '/analytics/saude-dados': typeof AnalyticsSaudeDadosRoute
  '/analytics/saude-sistema': typeof AnalyticsSaudeSistemaRoute
  '/configuracoes/contabil': typeof ConfiguracoesContabilRoute
  '/configuracoes/testes-carga': typeof ConfiguracoesTestesCargaRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
  '/paineis/$': typeof PaineisSplatRoute
  '/comercial/clientes/$clienteId': typeof ComercialClientesClienteIdRoute
  '/comercial/clientes/backfill': typeof ComercialClientesBackfillRoute
  '/comercial/contratos/$contratoId': typeof ComercialContratosContratoIdRoute
  '/comercial/projetos/$projetoId': typeof ComercialProjetosProjetoIdRoute
  '/engenharia/gestao-servicos/$osId': typeof EngenhariaGestaoServicosOsIdRoute
  '/engenharia/gestao-servicos/modelos': typeof EngenhariaGestaoServicosModelosRoute
  '/comercial/clientes/': typeof ComercialClientesIndexRoute
  '/comercial/contratos/': typeof ComercialContratosIndexRoute
  '/engenharia/gestao-servicos/': typeof EngenhariaGestaoServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/assinaturas': typeof AssinaturasRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/fornecedores': typeof FornecedoresRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/operacoes-financeiras': typeof OperacoesFinanceirasRoute
  '/paineis': typeof PaineisRouteWithChildren
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacoes-material': typeof SolicitacoesMaterialRoute
  '/suprimentos': typeof SuprimentosRoute
  '/tarefas': typeof TarefasRoute
  '/analytics/aprovacoes': typeof AnalyticsAprovacoesRoute
  '/analytics/comercial': typeof AnalyticsComercialRoute
  '/analytics/engenharia': typeof AnalyticsEngenhariaRoute
  '/analytics/erros': typeof AnalyticsErrosRoute
  '/analytics/estoque': typeof AnalyticsEstoqueRoute
  '/analytics/financeiro': typeof AnalyticsFinanceiroRoute
  '/analytics/financiamentos': typeof AnalyticsFinanciamentosRoute
  '/analytics/governanca': typeof AnalyticsGovernancaRoute
  '/analytics/performance': typeof AnalyticsPerformanceRoute
  '/analytics/posvenda': typeof AnalyticsPosvendaRoute
  '/analytics/saude-dados': typeof AnalyticsSaudeDadosRoute
  '/analytics/saude-sistema': typeof AnalyticsSaudeSistemaRoute
  '/configuracoes/contabil': typeof ConfiguracoesContabilRoute
  '/configuracoes/testes-carga': typeof ConfiguracoesTestesCargaRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
  '/paineis/$': typeof PaineisSplatRoute
  '/comercial/clientes/$clienteId': typeof ComercialClientesClienteIdRoute
  '/comercial/clientes/backfill': typeof ComercialClientesBackfillRoute
  '/comercial/contratos/$contratoId': typeof ComercialContratosContratoIdRoute
  '/comercial/projetos/$projetoId': typeof ComercialProjetosProjetoIdRoute
  '/engenharia/gestao-servicos/$osId': typeof EngenhariaGestaoServicosOsIdRoute
  '/engenharia/gestao-servicos/modelos': typeof EngenhariaGestaoServicosModelosRoute
  '/comercial/clientes': typeof ComercialClientesIndexRoute
  '/comercial/contratos': typeof ComercialContratosIndexRoute
  '/engenharia/gestao-servicos': typeof EngenhariaGestaoServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/assinaturas': typeof AssinaturasRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/fornecedores': typeof FornecedoresRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/operacoes-financeiras': typeof OperacoesFinanceirasRoute
  '/paineis': typeof PaineisRouteWithChildren
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacoes-material': typeof SolicitacoesMaterialRoute
  '/suprimentos': typeof SuprimentosRoute
  '/tarefas': typeof TarefasRoute
  '/analytics/aprovacoes': typeof AnalyticsAprovacoesRoute
  '/analytics/comercial': typeof AnalyticsComercialRoute
  '/analytics/engenharia': typeof AnalyticsEngenhariaRoute
  '/analytics/erros': typeof AnalyticsErrosRoute
  '/analytics/estoque': typeof AnalyticsEstoqueRoute
  '/analytics/financeiro': typeof AnalyticsFinanceiroRoute
  '/analytics/financiamentos': typeof AnalyticsFinanciamentosRoute
  '/analytics/governanca': typeof AnalyticsGovernancaRoute
  '/analytics/performance': typeof AnalyticsPerformanceRoute
  '/analytics/posvenda': typeof AnalyticsPosvendaRoute
  '/analytics/saude-dados': typeof AnalyticsSaudeDadosRoute
  '/analytics/saude-sistema': typeof AnalyticsSaudeSistemaRoute
  '/configuracoes/contabil': typeof ConfiguracoesContabilRoute
  '/configuracoes/testes-carga': typeof ConfiguracoesTestesCargaRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
  '/paineis/$': typeof PaineisSplatRoute
  '/comercial/clientes/$clienteId': typeof ComercialClientesClienteIdRoute
  '/comercial/clientes/backfill': typeof ComercialClientesBackfillRoute
  '/comercial/contratos/$contratoId': typeof ComercialContratosContratoIdRoute
  '/comercial/projetos/$projetoId': typeof ComercialProjetosProjetoIdRoute
  '/engenharia/gestao-servicos/$osId': typeof EngenhariaGestaoServicosOsIdRoute
  '/engenharia/gestao-servicos/modelos': typeof EngenhariaGestaoServicosModelosRoute
  '/comercial/clientes/': typeof ComercialClientesIndexRoute
  '/comercial/contratos/': typeof ComercialContratosIndexRoute
  '/engenharia/gestao-servicos/': typeof EngenhariaGestaoServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analises'
    | '/analytics'
    | '/aprovacoes'
    | '/assinaturas'
    | '/auditoria'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/fornecedores'
    | '/leads'
    | '/login'
    | '/notificacoes'
    | '/operacoes-financeiras'
    | '/paineis'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/reset-password'
    | '/solicitacoes-material'
    | '/suprimentos'
    | '/tarefas'
    | '/analytics/aprovacoes'
    | '/analytics/comercial'
    | '/analytics/engenharia'
    | '/analytics/erros'
    | '/analytics/estoque'
    | '/analytics/financeiro'
    | '/analytics/financiamentos'
    | '/analytics/governanca'
    | '/analytics/performance'
    | '/analytics/posvenda'
    | '/analytics/saude-dados'
    | '/analytics/saude-sistema'
    | '/configuracoes/contabil'
    | '/configuracoes/testes-carga'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
    | '/paineis/$'
    | '/comercial/clientes/$clienteId'
    | '/comercial/clientes/backfill'
    | '/comercial/contratos/$contratoId'
    | '/comercial/projetos/$projetoId'
    | '/engenharia/gestao-servicos/$osId'
    | '/engenharia/gestao-servicos/modelos'
    | '/comercial/clientes/'
    | '/comercial/contratos/'
    | '/engenharia/gestao-servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analises'
    | '/analytics'
    | '/aprovacoes'
    | '/assinaturas'
    | '/auditoria'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/fornecedores'
    | '/leads'
    | '/login'
    | '/notificacoes'
    | '/operacoes-financeiras'
    | '/paineis'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/reset-password'
    | '/solicitacoes-material'
    | '/suprimentos'
    | '/tarefas'
    | '/analytics/aprovacoes'
    | '/analytics/comercial'
    | '/analytics/engenharia'
    | '/analytics/erros'
    | '/analytics/estoque'
    | '/analytics/financeiro'
    | '/analytics/financiamentos'
    | '/analytics/governanca'
    | '/analytics/performance'
    | '/analytics/posvenda'
    | '/analytics/saude-dados'
    | '/analytics/saude-sistema'
    | '/configuracoes/contabil'
    | '/configuracoes/testes-carga'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
    | '/paineis/$'
    | '/comercial/clientes/$clienteId'
    | '/comercial/clientes/backfill'
    | '/comercial/contratos/$contratoId'
    | '/comercial/projetos/$projetoId'
    | '/engenharia/gestao-servicos/$osId'
    | '/engenharia/gestao-servicos/modelos'
    | '/comercial/clientes'
    | '/comercial/contratos'
    | '/engenharia/gestao-servicos'
  id:
    | '__root__'
    | '/'
    | '/analises'
    | '/analytics'
    | '/aprovacoes'
    | '/assinaturas'
    | '/auditoria'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/fornecedores'
    | '/leads'
    | '/login'
    | '/notificacoes'
    | '/operacoes-financeiras'
    | '/paineis'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/reset-password'
    | '/solicitacoes-material'
    | '/suprimentos'
    | '/tarefas'
    | '/analytics/aprovacoes'
    | '/analytics/comercial'
    | '/analytics/engenharia'
    | '/analytics/erros'
    | '/analytics/estoque'
    | '/analytics/financeiro'
    | '/analytics/financiamentos'
    | '/analytics/governanca'
    | '/analytics/performance'
    | '/analytics/posvenda'
    | '/analytics/saude-dados'
    | '/analytics/saude-sistema'
    | '/configuracoes/contabil'
    | '/configuracoes/testes-carga'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
    | '/paineis/$'
    | '/comercial/clientes/$clienteId'
    | '/comercial/clientes/backfill'
    | '/comercial/contratos/$contratoId'
    | '/comercial/projetos/$projetoId'
    | '/engenharia/gestao-servicos/$osId'
    | '/engenharia/gestao-servicos/modelos'
    | '/comercial/clientes/'
    | '/comercial/contratos/'
    | '/engenharia/gestao-servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisesRoute: typeof AnalisesRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AprovacoesRoute: typeof AprovacoesRoute
  AssinaturasRoute: typeof AssinaturasRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CadastrarRoute: typeof CadastrarRoute
  CadastrosRoute: typeof CadastrosRoute
  ComercialRoute: typeof ComercialRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DashboardsRoute: typeof DashboardsRouteWithChildren
  EngenhariaRoute: typeof EngenhariaRouteWithChildren
  EstoqueRoute: typeof EstoqueRoute
  EstoqueFundacaoRoute: typeof EstoqueFundacaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FinanceiroTitulosRoute: typeof FinanceiroTitulosRoute
  FinanciamentosRoute: typeof FinanciamentosRoute
  FornecedoresRoute: typeof FornecedoresRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OperacoesFinanceirasRoute: typeof OperacoesFinanceirasRoute
  PaineisRoute: typeof PaineisRouteWithChildren
  PedidosVendaRoute: typeof PedidosVendaRoute
  PosvendaRoute: typeof PosvendaRoute
  PropostasRoute: typeof PropostasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolicitacoesMaterialRoute: typeof SolicitacoesMaterialRoute
  SuprimentosRoute: typeof SuprimentosRoute
  TarefasRoute: typeof TarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suprimentos': {
      id: '/suprimentos'
      path: '/suprimentos'
      fullPath: '/suprimentos'
      preLoaderRoute: typeof SuprimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes-material': {
      id: '/solicitacoes-material'
      path: '/solicitacoes-material'
      fullPath: '/solicitacoes-material'
      preLoaderRoute: typeof SolicitacoesMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posvenda': {
      id: '/posvenda'
      path: '/posvenda'
      fullPath: '/posvenda'
      preLoaderRoute: typeof PosvendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-venda': {
      id: '/pedidos-venda'
      path: '/pedidos-venda'
      fullPath: '/pedidos-venda'
      preLoaderRoute: typeof PedidosVendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paineis': {
      id: '/paineis'
      path: '/paineis'
      fullPath: '/paineis'
      preLoaderRoute: typeof PaineisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes-financeiras': {
      id: '/operacoes-financeiras'
      path: '/operacoes-financeiras'
      fullPath: '/operacoes-financeiras'
      preLoaderRoute: typeof OperacoesFinanceirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos': {
      id: '/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof FinanciamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro-titulos': {
      id: '/financeiro-titulos'
      path: '/financeiro-titulos'
      fullPath: '/financeiro-titulos'
      preLoaderRoute: typeof FinanceiroTitulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-fundacao': {
      id: '/estoque-fundacao'
      path: '/estoque-fundacao'
      fullPath: '/estoque-fundacao'
      preLoaderRoute: typeof EstoqueFundacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinaturas': {
      id: '/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises': {
      id: '/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paineis/$': {
      id: '/paineis/$'
      path: '/$'
      fullPath: '/paineis/$'
      preLoaderRoute: typeof PaineisSplatRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/dashboards/posvenda': {
      id: '/dashboards/posvenda'
      path: '/posvenda'
      fullPath: '/dashboards/posvenda'
      preLoaderRoute: typeof DashboardsPosvendaRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/financiamentos': {
      id: '/dashboards/financiamentos'
      path: '/financiamentos'
      fullPath: '/dashboards/financiamentos'
      preLoaderRoute: typeof DashboardsFinanciamentosRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/financeiro': {
      id: '/dashboards/financeiro'
      path: '/financeiro'
      fullPath: '/dashboards/financeiro'
      preLoaderRoute: typeof DashboardsFinanceiroRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/estoque': {
      id: '/dashboards/estoque'
      path: '/estoque'
      fullPath: '/dashboards/estoque'
      preLoaderRoute: typeof DashboardsEstoqueRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/engenharia': {
      id: '/dashboards/engenharia'
      path: '/engenharia'
      fullPath: '/dashboards/engenharia'
      preLoaderRoute: typeof DashboardsEngenhariaRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/comercial': {
      id: '/dashboards/comercial'
      path: '/comercial'
      fullPath: '/dashboards/comercial'
      preLoaderRoute: typeof DashboardsComercialRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/aprovacoes': {
      id: '/dashboards/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/dashboards/aprovacoes'
      preLoaderRoute: typeof DashboardsAprovacoesRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/configuracoes/testes-carga': {
      id: '/configuracoes/testes-carga'
      path: '/testes-carga'
      fullPath: '/configuracoes/testes-carga'
      preLoaderRoute: typeof ConfiguracoesTestesCargaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/contabil': {
      id: '/configuracoes/contabil'
      path: '/contabil'
      fullPath: '/configuracoes/contabil'
      preLoaderRoute: typeof ConfiguracoesContabilRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/analytics/saude-sistema': {
      id: '/analytics/saude-sistema'
      path: '/saude-sistema'
      fullPath: '/analytics/saude-sistema'
      preLoaderRoute: typeof AnalyticsSaudeSistemaRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/saude-dados': {
      id: '/analytics/saude-dados'
      path: '/saude-dados'
      fullPath: '/analytics/saude-dados'
      preLoaderRoute: typeof AnalyticsSaudeDadosRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/posvenda': {
      id: '/analytics/posvenda'
      path: '/posvenda'
      fullPath: '/analytics/posvenda'
      preLoaderRoute: typeof AnalyticsPosvendaRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/performance': {
      id: '/analytics/performance'
      path: '/performance'
      fullPath: '/analytics/performance'
      preLoaderRoute: typeof AnalyticsPerformanceRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/governanca': {
      id: '/analytics/governanca'
      path: '/governanca'
      fullPath: '/analytics/governanca'
      preLoaderRoute: typeof AnalyticsGovernancaRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/financiamentos': {
      id: '/analytics/financiamentos'
      path: '/financiamentos'
      fullPath: '/analytics/financiamentos'
      preLoaderRoute: typeof AnalyticsFinanciamentosRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/financeiro': {
      id: '/analytics/financeiro'
      path: '/financeiro'
      fullPath: '/analytics/financeiro'
      preLoaderRoute: typeof AnalyticsFinanceiroRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/estoque': {
      id: '/analytics/estoque'
      path: '/estoque'
      fullPath: '/analytics/estoque'
      preLoaderRoute: typeof AnalyticsEstoqueRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/erros': {
      id: '/analytics/erros'
      path: '/erros'
      fullPath: '/analytics/erros'
      preLoaderRoute: typeof AnalyticsErrosRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/engenharia': {
      id: '/analytics/engenharia'
      path: '/engenharia'
      fullPath: '/analytics/engenharia'
      preLoaderRoute: typeof AnalyticsEngenhariaRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/comercial': {
      id: '/analytics/comercial'
      path: '/comercial'
      fullPath: '/analytics/comercial'
      preLoaderRoute: typeof AnalyticsComercialRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/aprovacoes': {
      id: '/analytics/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/analytics/aprovacoes'
      preLoaderRoute: typeof AnalyticsAprovacoesRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/engenharia/gestao-servicos/': {
      id: '/engenharia/gestao-servicos/'
      path: '/gestao-servicos'
      fullPath: '/engenharia/gestao-servicos/'
      preLoaderRoute: typeof EngenhariaGestaoServicosIndexRouteImport
      parentRoute: typeof EngenhariaRoute
    }
    '/comercial/contratos/': {
      id: '/comercial/contratos/'
      path: '/contratos'
      fullPath: '/comercial/contratos/'
      preLoaderRoute: typeof ComercialContratosIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/clientes/': {
      id: '/comercial/clientes/'
      path: '/clientes'
      fullPath: '/comercial/clientes/'
      preLoaderRoute: typeof ComercialClientesIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/engenharia/gestao-servicos/modelos': {
      id: '/engenharia/gestao-servicos/modelos'
      path: '/gestao-servicos/modelos'
      fullPath: '/engenharia/gestao-servicos/modelos'
      preLoaderRoute: typeof EngenhariaGestaoServicosModelosRouteImport
      parentRoute: typeof EngenhariaRoute
    }
    '/engenharia/gestao-servicos/$osId': {
      id: '/engenharia/gestao-servicos/$osId'
      path: '/gestao-servicos/$osId'
      fullPath: '/engenharia/gestao-servicos/$osId'
      preLoaderRoute: typeof EngenhariaGestaoServicosOsIdRouteImport
      parentRoute: typeof EngenhariaRoute
    }
    '/comercial/projetos/$projetoId': {
      id: '/comercial/projetos/$projetoId'
      path: '/projetos/$projetoId'
      fullPath: '/comercial/projetos/$projetoId'
      preLoaderRoute: typeof ComercialProjetosProjetoIdRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/contratos/$contratoId': {
      id: '/comercial/contratos/$contratoId'
      path: '/contratos/$contratoId'
      fullPath: '/comercial/contratos/$contratoId'
      preLoaderRoute: typeof ComercialContratosContratoIdRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/clientes/backfill': {
      id: '/comercial/clientes/backfill'
      path: '/clientes/backfill'
      fullPath: '/comercial/clientes/backfill'
      preLoaderRoute: typeof ComercialClientesBackfillRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/clientes/$clienteId': {
      id: '/comercial/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/comercial/clientes/$clienteId'
      preLoaderRoute: typeof ComercialClientesClienteIdRouteImport
      parentRoute: typeof ComercialRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsAprovacoesRoute: typeof AnalyticsAprovacoesRoute
  AnalyticsComercialRoute: typeof AnalyticsComercialRoute
  AnalyticsEngenhariaRoute: typeof AnalyticsEngenhariaRoute
  AnalyticsErrosRoute: typeof AnalyticsErrosRoute
  AnalyticsEstoqueRoute: typeof AnalyticsEstoqueRoute
  AnalyticsFinanceiroRoute: typeof AnalyticsFinanceiroRoute
  AnalyticsFinanciamentosRoute: typeof AnalyticsFinanciamentosRoute
  AnalyticsGovernancaRoute: typeof AnalyticsGovernancaRoute
  AnalyticsPerformanceRoute: typeof AnalyticsPerformanceRoute
  AnalyticsPosvendaRoute: typeof AnalyticsPosvendaRoute
  AnalyticsSaudeDadosRoute: typeof AnalyticsSaudeDadosRoute
  AnalyticsSaudeSistemaRoute: typeof AnalyticsSaudeSistemaRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsAprovacoesRoute: AnalyticsAprovacoesRoute,
  AnalyticsComercialRoute: AnalyticsComercialRoute,
  AnalyticsEngenhariaRoute: AnalyticsEngenhariaRoute,
  AnalyticsErrosRoute: AnalyticsErrosRoute,
  AnalyticsEstoqueRoute: AnalyticsEstoqueRoute,
  AnalyticsFinanceiroRoute: AnalyticsFinanceiroRoute,
  AnalyticsFinanciamentosRoute: AnalyticsFinanciamentosRoute,
  AnalyticsGovernancaRoute: AnalyticsGovernancaRoute,
  AnalyticsPerformanceRoute: AnalyticsPerformanceRoute,
  AnalyticsPosvendaRoute: AnalyticsPosvendaRoute,
  AnalyticsSaudeDadosRoute: AnalyticsSaudeDadosRoute,
  AnalyticsSaudeSistemaRoute: AnalyticsSaudeSistemaRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface ComercialRouteChildren {
  ComercialClientesClienteIdRoute: typeof ComercialClientesClienteIdRoute
  ComercialClientesBackfillRoute: typeof ComercialClientesBackfillRoute
  ComercialContratosContratoIdRoute: typeof ComercialContratosContratoIdRoute
  ComercialProjetosProjetoIdRoute: typeof ComercialProjetosProjetoIdRoute
  ComercialClientesIndexRoute: typeof ComercialClientesIndexRoute
  ComercialContratosIndexRoute: typeof ComercialContratosIndexRoute
}

const ComercialRouteChildren: ComercialRouteChildren = {
  ComercialClientesClienteIdRoute: ComercialClientesClienteIdRoute,
  ComercialClientesBackfillRoute: ComercialClientesBackfillRoute,
  ComercialContratosContratoIdRoute: ComercialContratosContratoIdRoute,
  ComercialProjetosProjetoIdRoute: ComercialProjetosProjetoIdRoute,
  ComercialClientesIndexRoute: ComercialClientesIndexRoute,
  ComercialContratosIndexRoute: ComercialContratosIndexRoute,
}

const ComercialRouteWithChildren = ComercialRoute._addFileChildren(
  ComercialRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesContabilRoute: typeof ConfiguracoesContabilRoute
  ConfiguracoesTestesCargaRoute: typeof ConfiguracoesTestesCargaRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesContabilRoute: ConfiguracoesContabilRoute,
  ConfiguracoesTestesCargaRoute: ConfiguracoesTestesCargaRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface DashboardsRouteChildren {
  DashboardsAprovacoesRoute: typeof DashboardsAprovacoesRoute
  DashboardsComercialRoute: typeof DashboardsComercialRoute
  DashboardsEngenhariaRoute: typeof DashboardsEngenhariaRoute
  DashboardsEstoqueRoute: typeof DashboardsEstoqueRoute
  DashboardsFinanceiroRoute: typeof DashboardsFinanceiroRoute
  DashboardsFinanciamentosRoute: typeof DashboardsFinanciamentosRoute
  DashboardsPosvendaRoute: typeof DashboardsPosvendaRoute
}

const DashboardsRouteChildren: DashboardsRouteChildren = {
  DashboardsAprovacoesRoute: DashboardsAprovacoesRoute,
  DashboardsComercialRoute: DashboardsComercialRoute,
  DashboardsEngenhariaRoute: DashboardsEngenhariaRoute,
  DashboardsEstoqueRoute: DashboardsEstoqueRoute,
  DashboardsFinanceiroRoute: DashboardsFinanceiroRoute,
  DashboardsFinanciamentosRoute: DashboardsFinanciamentosRoute,
  DashboardsPosvendaRoute: DashboardsPosvendaRoute,
}

const DashboardsRouteWithChildren = DashboardsRoute._addFileChildren(
  DashboardsRouteChildren,
)

interface EngenhariaRouteChildren {
  EngenhariaGestaoServicosOsIdRoute: typeof EngenhariaGestaoServicosOsIdRoute
  EngenhariaGestaoServicosModelosRoute: typeof EngenhariaGestaoServicosModelosRoute
  EngenhariaGestaoServicosIndexRoute: typeof EngenhariaGestaoServicosIndexRoute
}

const EngenhariaRouteChildren: EngenhariaRouteChildren = {
  EngenhariaGestaoServicosOsIdRoute: EngenhariaGestaoServicosOsIdRoute,
  EngenhariaGestaoServicosModelosRoute: EngenhariaGestaoServicosModelosRoute,
  EngenhariaGestaoServicosIndexRoute: EngenhariaGestaoServicosIndexRoute,
}

const EngenhariaRouteWithChildren = EngenhariaRoute._addFileChildren(
  EngenhariaRouteChildren,
)

interface PaineisRouteChildren {
  PaineisSplatRoute: typeof PaineisSplatRoute
}

const PaineisRouteChildren: PaineisRouteChildren = {
  PaineisSplatRoute: PaineisSplatRoute,
}

const PaineisRouteWithChildren =
  PaineisRoute._addFileChildren(PaineisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisesRoute: AnalisesRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AprovacoesRoute: AprovacoesRoute,
  AssinaturasRoute: AssinaturasRoute,
  AuditoriaRoute: AuditoriaRoute,
  CadastrarRoute: CadastrarRoute,
  CadastrosRoute: CadastrosRoute,
  ComercialRoute: ComercialRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DashboardsRoute: DashboardsRouteWithChildren,
  EngenhariaRoute: EngenhariaRouteWithChildren,
  EstoqueRoute: EstoqueRoute,
  EstoqueFundacaoRoute: EstoqueFundacaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  FinanceiroTitulosRoute: FinanceiroTitulosRoute,
  FinanciamentosRoute: FinanciamentosRoute,
  FornecedoresRoute: FornecedoresRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  NotificacoesRoute: NotificacoesRoute,
  OperacoesFinanceirasRoute: OperacoesFinanceirasRoute,
  PaineisRoute: PaineisRouteWithChildren,
  PedidosVendaRoute: PedidosVendaRoute,
  PosvendaRoute: PosvendaRoute,
  PropostasRoute: PropostasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolicitacoesMaterialRoute: SolicitacoesMaterialRoute,
  SuprimentosRoute: SuprimentosRoute,
  TarefasRoute: TarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
