/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PosvendaRouteImport } from './routes/posvenda'
import { Route as PedidosVendaRouteImport } from './routes/pedidos-venda'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FinanciamentosRouteImport } from './routes/financiamentos'
import { Route as FinanceiroTitulosRouteImport } from './routes/financeiro-titulos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueFundacaoRouteImport } from './routes/estoque-fundacao'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EngenhariaRouteImport } from './routes/engenharia'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardsPosvendaRouteImport } from './routes/dashboards.posvenda'
import { Route as DashboardsFinanciamentosRouteImport } from './routes/dashboards.financiamentos'
import { Route as DashboardsFinanceiroRouteImport } from './routes/dashboards.financeiro'
import { Route as DashboardsEstoqueRouteImport } from './routes/dashboards.estoque'
import { Route as DashboardsEngenhariaRouteImport } from './routes/dashboards.engenharia'
import { Route as DashboardsComercialRouteImport } from './routes/dashboards.comercial'
import { Route as DashboardsAprovacoesRouteImport } from './routes/dashboards.aprovacoes'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PosvendaRoute = PosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosVendaRoute = PedidosVendaRouteImport.update({
  id: '/pedidos-venda',
  path: '/pedidos-venda',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentosRoute = FinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroTitulosRoute = FinanceiroTitulosRouteImport.update({
  id: '/financeiro-titulos',
  path: '/financeiro-titulos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueFundacaoRoute = EstoqueFundacaoRouteImport.update({
  id: '/estoque-fundacao',
  path: '/estoque-fundacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRoute = EngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsPosvendaRoute = DashboardsPosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsFinanciamentosRoute =
  DashboardsFinanciamentosRouteImport.update({
    id: '/financiamentos',
    path: '/financiamentos',
    getParentRoute: () => DashboardsRoute,
  } as any)
const DashboardsFinanceiroRoute = DashboardsFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsEstoqueRoute = DashboardsEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsEngenhariaRoute = DashboardsEngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsComercialRoute = DashboardsComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsAprovacoesRoute = DashboardsAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => DashboardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRoute
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRoute
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRoute
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/aprovacoes'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/leads'
    | '/login'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/tarefas'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/aprovacoes'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/leads'
    | '/login'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/tarefas'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/aprovacoes'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/leads'
    | '/login'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/tarefas'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AprovacoesRoute: typeof AprovacoesRoute
  CadastrarRoute: typeof CadastrarRoute
  CadastrosRoute: typeof CadastrosRoute
  ComercialRoute: typeof ComercialRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  DashboardsRoute: typeof DashboardsRouteWithChildren
  EngenhariaRoute: typeof EngenhariaRoute
  EstoqueRoute: typeof EstoqueRoute
  EstoqueFundacaoRoute: typeof EstoqueFundacaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FinanceiroTitulosRoute: typeof FinanceiroTitulosRoute
  FinanciamentosRoute: typeof FinanciamentosRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PedidosVendaRoute: typeof PedidosVendaRoute
  PosvendaRoute: typeof PosvendaRoute
  PropostasRoute: typeof PropostasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TarefasRoute: typeof TarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posvenda': {
      id: '/posvenda'
      path: '/posvenda'
      fullPath: '/posvenda'
      preLoaderRoute: typeof PosvendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-venda': {
      id: '/pedidos-venda'
      path: '/pedidos-venda'
      fullPath: '/pedidos-venda'
      preLoaderRoute: typeof PedidosVendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos': {
      id: '/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof FinanciamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro-titulos': {
      id: '/financeiro-titulos'
      path: '/financeiro-titulos'
      fullPath: '/financeiro-titulos'
      preLoaderRoute: typeof FinanceiroTitulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-fundacao': {
      id: '/estoque-fundacao'
      path: '/estoque-fundacao'
      fullPath: '/estoque-fundacao'
      preLoaderRoute: typeof EstoqueFundacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/posvenda': {
      id: '/dashboards/posvenda'
      path: '/posvenda'
      fullPath: '/dashboards/posvenda'
      preLoaderRoute: typeof DashboardsPosvendaRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/financiamentos': {
      id: '/dashboards/financiamentos'
      path: '/financiamentos'
      fullPath: '/dashboards/financiamentos'
      preLoaderRoute: typeof DashboardsFinanciamentosRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/financeiro': {
      id: '/dashboards/financeiro'
      path: '/financeiro'
      fullPath: '/dashboards/financeiro'
      preLoaderRoute: typeof DashboardsFinanceiroRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/estoque': {
      id: '/dashboards/estoque'
      path: '/estoque'
      fullPath: '/dashboards/estoque'
      preLoaderRoute: typeof DashboardsEstoqueRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/engenharia': {
      id: '/dashboards/engenharia'
      path: '/engenharia'
      fullPath: '/dashboards/engenharia'
      preLoaderRoute: typeof DashboardsEngenhariaRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/comercial': {
      id: '/dashboards/comercial'
      path: '/comercial'
      fullPath: '/dashboards/comercial'
      preLoaderRoute: typeof DashboardsComercialRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/aprovacoes': {
      id: '/dashboards/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/dashboards/aprovacoes'
      preLoaderRoute: typeof DashboardsAprovacoesRouteImport
      parentRoute: typeof DashboardsRoute
    }
  }
}

interface DashboardsRouteChildren {
  DashboardsAprovacoesRoute: typeof DashboardsAprovacoesRoute
  DashboardsComercialRoute: typeof DashboardsComercialRoute
  DashboardsEngenhariaRoute: typeof DashboardsEngenhariaRoute
  DashboardsEstoqueRoute: typeof DashboardsEstoqueRoute
  DashboardsFinanceiroRoute: typeof DashboardsFinanceiroRoute
  DashboardsFinanciamentosRoute: typeof DashboardsFinanciamentosRoute
  DashboardsPosvendaRoute: typeof DashboardsPosvendaRoute
}

const DashboardsRouteChildren: DashboardsRouteChildren = {
  DashboardsAprovacoesRoute: DashboardsAprovacoesRoute,
  DashboardsComercialRoute: DashboardsComercialRoute,
  DashboardsEngenhariaRoute: DashboardsEngenhariaRoute,
  DashboardsEstoqueRoute: DashboardsEstoqueRoute,
  DashboardsFinanceiroRoute: DashboardsFinanceiroRoute,
  DashboardsFinanciamentosRoute: DashboardsFinanciamentosRoute,
  DashboardsPosvendaRoute: DashboardsPosvendaRoute,
}

const DashboardsRouteWithChildren = DashboardsRoute._addFileChildren(
  DashboardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AprovacoesRoute: AprovacoesRoute,
  CadastrarRoute: CadastrarRoute,
  CadastrosRoute: CadastrosRoute,
  ComercialRoute: ComercialRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  DashboardsRoute: DashboardsRouteWithChildren,
  EngenhariaRoute: EngenhariaRoute,
  EstoqueRoute: EstoqueRoute,
  EstoqueFundacaoRoute: EstoqueFundacaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  FinanceiroTitulosRoute: FinanceiroTitulosRoute,
  FinanciamentosRoute: FinanciamentosRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PedidosVendaRoute: PedidosVendaRoute,
  PosvendaRoute: PosvendaRoute,
  PropostasRoute: PropostasRoute,
  RelatoriosRoute: RelatoriosRoute,
  TarefasRoute: TarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
