/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SolicitacoesMaterialRouteImport } from './routes/solicitacoes-material'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PosvendaRouteImport } from './routes/posvenda'
import { Route as PedidosVendaRouteImport } from './routes/pedidos-venda'
import { Route as PaineisRouteImport } from './routes/paineis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FinanciamentosRouteImport } from './routes/financiamentos'
import { Route as FinanceiroTitulosRouteImport } from './routes/financeiro-titulos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueFundacaoRouteImport } from './routes/estoque-fundacao'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EngenhariaRouteImport } from './routes/engenharia'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnalisesRouteImport } from './routes/analises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaineisPosvendaRouteImport } from './routes/paineis.posvenda'
import { Route as PaineisFinanciamentosRouteImport } from './routes/paineis.financiamentos'
import { Route as PaineisFinanceiroRouteImport } from './routes/paineis.financeiro'
import { Route as PaineisEstoqueRouteImport } from './routes/paineis.estoque'
import { Route as PaineisEngenhariaRouteImport } from './routes/paineis.engenharia'
import { Route as PaineisComercialRouteImport } from './routes/paineis.comercial'
import { Route as PaineisAprovacoesRouteImport } from './routes/paineis.aprovacoes'
import { Route as DashboardsPosvendaRouteImport } from './routes/dashboards.posvenda'
import { Route as DashboardsFinanciamentosRouteImport } from './routes/dashboards.financiamentos'
import { Route as DashboardsFinanceiroRouteImport } from './routes/dashboards.financeiro'
import { Route as DashboardsEstoqueRouteImport } from './routes/dashboards.estoque'
import { Route as DashboardsEngenhariaRouteImport } from './routes/dashboards.engenharia'
import { Route as DashboardsComercialRouteImport } from './routes/dashboards.comercial'
import { Route as DashboardsAprovacoesRouteImport } from './routes/dashboards.aprovacoes'
import { Route as AnalyticsPosvendaRouteImport } from './routes/analytics.posvenda'
import { Route as AnalyticsFinanciamentosRouteImport } from './routes/analytics.financiamentos'
import { Route as AnalyticsFinanceiroRouteImport } from './routes/analytics.financeiro'
import { Route as AnalyticsEstoqueRouteImport } from './routes/analytics.estoque'
import { Route as AnalyticsEngenhariaRouteImport } from './routes/analytics.engenharia'
import { Route as AnalyticsComercialRouteImport } from './routes/analytics.comercial'
import { Route as AnalyticsAprovacoesRouteImport } from './routes/analytics.aprovacoes'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesMaterialRoute = SolicitacoesMaterialRouteImport.update({
  id: '/solicitacoes-material',
  path: '/solicitacoes-material',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PosvendaRoute = PosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosVendaRoute = PedidosVendaRouteImport.update({
  id: '/pedidos-venda',
  path: '/pedidos-venda',
  getParentRoute: () => rootRouteImport,
} as any)
const PaineisRoute = PaineisRouteImport.update({
  id: '/paineis',
  path: '/paineis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentosRoute = FinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroTitulosRoute = FinanceiroTitulosRouteImport.update({
  id: '/financeiro-titulos',
  path: '/financeiro-titulos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueFundacaoRoute = EstoqueFundacaoRouteImport.update({
  id: '/estoque-fundacao',
  path: '/estoque-fundacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRoute = EngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesRoute = AnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaineisPosvendaRoute = PaineisPosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => PaineisRoute,
} as any)
const PaineisFinanciamentosRoute = PaineisFinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => PaineisRoute,
} as any)
const PaineisFinanceiroRoute = PaineisFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PaineisRoute,
} as any)
const PaineisEstoqueRoute = PaineisEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => PaineisRoute,
} as any)
const PaineisEngenhariaRoute = PaineisEngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => PaineisRoute,
} as any)
const PaineisComercialRoute = PaineisComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => PaineisRoute,
} as any)
const PaineisAprovacoesRoute = PaineisAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => PaineisRoute,
} as any)
const DashboardsPosvendaRoute = DashboardsPosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsFinanciamentosRoute =
  DashboardsFinanciamentosRouteImport.update({
    id: '/financiamentos',
    path: '/financiamentos',
    getParentRoute: () => DashboardsRoute,
  } as any)
const DashboardsFinanceiroRoute = DashboardsFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsEstoqueRoute = DashboardsEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsEngenhariaRoute = DashboardsEngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsComercialRoute = DashboardsComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => DashboardsRoute,
} as any)
const DashboardsAprovacoesRoute = DashboardsAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => DashboardsRoute,
} as any)
const AnalyticsPosvendaRoute = AnalyticsPosvendaRouteImport.update({
  id: '/posvenda',
  path: '/posvenda',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsFinanciamentosRoute = AnalyticsFinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsFinanceiroRoute = AnalyticsFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsEstoqueRoute = AnalyticsEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsEngenhariaRoute = AnalyticsEngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsComercialRoute = AnalyticsComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsAprovacoesRoute = AnalyticsAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AnalyticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRoute
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/paineis': typeof PaineisRouteWithChildren
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/solicitacoes-material': typeof SolicitacoesMaterialRoute
  '/tarefas': typeof TarefasRoute
  '/analytics/aprovacoes': typeof AnalyticsAprovacoesRoute
  '/analytics/comercial': typeof AnalyticsComercialRoute
  '/analytics/engenharia': typeof AnalyticsEngenhariaRoute
  '/analytics/estoque': typeof AnalyticsEstoqueRoute
  '/analytics/financeiro': typeof AnalyticsFinanceiroRoute
  '/analytics/financiamentos': typeof AnalyticsFinanciamentosRoute
  '/analytics/posvenda': typeof AnalyticsPosvendaRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
  '/paineis/aprovacoes': typeof PaineisAprovacoesRoute
  '/paineis/comercial': typeof PaineisComercialRoute
  '/paineis/engenharia': typeof PaineisEngenhariaRoute
  '/paineis/estoque': typeof PaineisEstoqueRoute
  '/paineis/financeiro': typeof PaineisFinanceiroRoute
  '/paineis/financiamentos': typeof PaineisFinanciamentosRoute
  '/paineis/posvenda': typeof PaineisPosvendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRoute
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/paineis': typeof PaineisRouteWithChildren
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/solicitacoes-material': typeof SolicitacoesMaterialRoute
  '/tarefas': typeof TarefasRoute
  '/analytics/aprovacoes': typeof AnalyticsAprovacoesRoute
  '/analytics/comercial': typeof AnalyticsComercialRoute
  '/analytics/engenharia': typeof AnalyticsEngenhariaRoute
  '/analytics/estoque': typeof AnalyticsEstoqueRoute
  '/analytics/financeiro': typeof AnalyticsFinanceiroRoute
  '/analytics/financiamentos': typeof AnalyticsFinanciamentosRoute
  '/analytics/posvenda': typeof AnalyticsPosvendaRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
  '/paineis/aprovacoes': typeof PaineisAprovacoesRoute
  '/paineis/comercial': typeof PaineisComercialRoute
  '/paineis/engenharia': typeof PaineisEngenhariaRoute
  '/paineis/estoque': typeof PaineisEstoqueRoute
  '/paineis/financeiro': typeof PaineisFinanceiroRoute
  '/paineis/financiamentos': typeof PaineisFinanciamentosRoute
  '/paineis/posvenda': typeof PaineisPosvendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastros': typeof CadastrosRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/engenharia': typeof EngenhariaRoute
  '/estoque': typeof EstoqueRoute
  '/estoque-fundacao': typeof EstoqueFundacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/financeiro-titulos': typeof FinanceiroTitulosRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/paineis': typeof PaineisRouteWithChildren
  '/pedidos-venda': typeof PedidosVendaRoute
  '/posvenda': typeof PosvendaRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/solicitacoes-material': typeof SolicitacoesMaterialRoute
  '/tarefas': typeof TarefasRoute
  '/analytics/aprovacoes': typeof AnalyticsAprovacoesRoute
  '/analytics/comercial': typeof AnalyticsComercialRoute
  '/analytics/engenharia': typeof AnalyticsEngenhariaRoute
  '/analytics/estoque': typeof AnalyticsEstoqueRoute
  '/analytics/financeiro': typeof AnalyticsFinanceiroRoute
  '/analytics/financiamentos': typeof AnalyticsFinanciamentosRoute
  '/analytics/posvenda': typeof AnalyticsPosvendaRoute
  '/dashboards/aprovacoes': typeof DashboardsAprovacoesRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/engenharia': typeof DashboardsEngenhariaRoute
  '/dashboards/estoque': typeof DashboardsEstoqueRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/financiamentos': typeof DashboardsFinanciamentosRoute
  '/dashboards/posvenda': typeof DashboardsPosvendaRoute
  '/paineis/aprovacoes': typeof PaineisAprovacoesRoute
  '/paineis/comercial': typeof PaineisComercialRoute
  '/paineis/engenharia': typeof PaineisEngenhariaRoute
  '/paineis/estoque': typeof PaineisEstoqueRoute
  '/paineis/financeiro': typeof PaineisFinanceiroRoute
  '/paineis/financiamentos': typeof PaineisFinanciamentosRoute
  '/paineis/posvenda': typeof PaineisPosvendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analises'
    | '/analytics'
    | '/aprovacoes'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/leads'
    | '/login'
    | '/paineis'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/solicitacoes-material'
    | '/tarefas'
    | '/analytics/aprovacoes'
    | '/analytics/comercial'
    | '/analytics/engenharia'
    | '/analytics/estoque'
    | '/analytics/financeiro'
    | '/analytics/financiamentos'
    | '/analytics/posvenda'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
    | '/paineis/aprovacoes'
    | '/paineis/comercial'
    | '/paineis/engenharia'
    | '/paineis/estoque'
    | '/paineis/financeiro'
    | '/paineis/financiamentos'
    | '/paineis/posvenda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analises'
    | '/analytics'
    | '/aprovacoes'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/leads'
    | '/login'
    | '/paineis'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/solicitacoes-material'
    | '/tarefas'
    | '/analytics/aprovacoes'
    | '/analytics/comercial'
    | '/analytics/engenharia'
    | '/analytics/estoque'
    | '/analytics/financeiro'
    | '/analytics/financiamentos'
    | '/analytics/posvenda'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
    | '/paineis/aprovacoes'
    | '/paineis/comercial'
    | '/paineis/engenharia'
    | '/paineis/estoque'
    | '/paineis/financeiro'
    | '/paineis/financiamentos'
    | '/paineis/posvenda'
  id:
    | '__root__'
    | '/'
    | '/analises'
    | '/analytics'
    | '/aprovacoes'
    | '/cadastrar'
    | '/cadastros'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/estoque'
    | '/estoque-fundacao'
    | '/financeiro'
    | '/financeiro-titulos'
    | '/financiamentos'
    | '/leads'
    | '/login'
    | '/paineis'
    | '/pedidos-venda'
    | '/posvenda'
    | '/propostas'
    | '/relatorios'
    | '/solicitacoes-material'
    | '/tarefas'
    | '/analytics/aprovacoes'
    | '/analytics/comercial'
    | '/analytics/engenharia'
    | '/analytics/estoque'
    | '/analytics/financeiro'
    | '/analytics/financiamentos'
    | '/analytics/posvenda'
    | '/dashboards/aprovacoes'
    | '/dashboards/comercial'
    | '/dashboards/engenharia'
    | '/dashboards/estoque'
    | '/dashboards/financeiro'
    | '/dashboards/financiamentos'
    | '/dashboards/posvenda'
    | '/paineis/aprovacoes'
    | '/paineis/comercial'
    | '/paineis/engenharia'
    | '/paineis/estoque'
    | '/paineis/financeiro'
    | '/paineis/financiamentos'
    | '/paineis/posvenda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisesRoute: typeof AnalisesRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AprovacoesRoute: typeof AprovacoesRoute
  CadastrarRoute: typeof CadastrarRoute
  CadastrosRoute: typeof CadastrosRoute
  ComercialRoute: typeof ComercialRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  DashboardsRoute: typeof DashboardsRouteWithChildren
  EngenhariaRoute: typeof EngenhariaRoute
  EstoqueRoute: typeof EstoqueRoute
  EstoqueFundacaoRoute: typeof EstoqueFundacaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FinanceiroTitulosRoute: typeof FinanceiroTitulosRoute
  FinanciamentosRoute: typeof FinanciamentosRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PaineisRoute: typeof PaineisRouteWithChildren
  PedidosVendaRoute: typeof PedidosVendaRoute
  PosvendaRoute: typeof PosvendaRoute
  PropostasRoute: typeof PropostasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SolicitacoesMaterialRoute: typeof SolicitacoesMaterialRoute
  TarefasRoute: typeof TarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes-material': {
      id: '/solicitacoes-material'
      path: '/solicitacoes-material'
      fullPath: '/solicitacoes-material'
      preLoaderRoute: typeof SolicitacoesMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posvenda': {
      id: '/posvenda'
      path: '/posvenda'
      fullPath: '/posvenda'
      preLoaderRoute: typeof PosvendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-venda': {
      id: '/pedidos-venda'
      path: '/pedidos-venda'
      fullPath: '/pedidos-venda'
      preLoaderRoute: typeof PedidosVendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paineis': {
      id: '/paineis'
      path: '/paineis'
      fullPath: '/paineis'
      preLoaderRoute: typeof PaineisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos': {
      id: '/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof FinanciamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro-titulos': {
      id: '/financeiro-titulos'
      path: '/financeiro-titulos'
      fullPath: '/financeiro-titulos'
      preLoaderRoute: typeof FinanceiroTitulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-fundacao': {
      id: '/estoque-fundacao'
      path: '/estoque-fundacao'
      fullPath: '/estoque-fundacao'
      preLoaderRoute: typeof EstoqueFundacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises': {
      id: '/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paineis/posvenda': {
      id: '/paineis/posvenda'
      path: '/posvenda'
      fullPath: '/paineis/posvenda'
      preLoaderRoute: typeof PaineisPosvendaRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/paineis/financiamentos': {
      id: '/paineis/financiamentos'
      path: '/financiamentos'
      fullPath: '/paineis/financiamentos'
      preLoaderRoute: typeof PaineisFinanciamentosRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/paineis/financeiro': {
      id: '/paineis/financeiro'
      path: '/financeiro'
      fullPath: '/paineis/financeiro'
      preLoaderRoute: typeof PaineisFinanceiroRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/paineis/estoque': {
      id: '/paineis/estoque'
      path: '/estoque'
      fullPath: '/paineis/estoque'
      preLoaderRoute: typeof PaineisEstoqueRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/paineis/engenharia': {
      id: '/paineis/engenharia'
      path: '/engenharia'
      fullPath: '/paineis/engenharia'
      preLoaderRoute: typeof PaineisEngenhariaRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/paineis/comercial': {
      id: '/paineis/comercial'
      path: '/comercial'
      fullPath: '/paineis/comercial'
      preLoaderRoute: typeof PaineisComercialRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/paineis/aprovacoes': {
      id: '/paineis/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/paineis/aprovacoes'
      preLoaderRoute: typeof PaineisAprovacoesRouteImport
      parentRoute: typeof PaineisRoute
    }
    '/dashboards/posvenda': {
      id: '/dashboards/posvenda'
      path: '/posvenda'
      fullPath: '/dashboards/posvenda'
      preLoaderRoute: typeof DashboardsPosvendaRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/financiamentos': {
      id: '/dashboards/financiamentos'
      path: '/financiamentos'
      fullPath: '/dashboards/financiamentos'
      preLoaderRoute: typeof DashboardsFinanciamentosRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/financeiro': {
      id: '/dashboards/financeiro'
      path: '/financeiro'
      fullPath: '/dashboards/financeiro'
      preLoaderRoute: typeof DashboardsFinanceiroRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/estoque': {
      id: '/dashboards/estoque'
      path: '/estoque'
      fullPath: '/dashboards/estoque'
      preLoaderRoute: typeof DashboardsEstoqueRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/engenharia': {
      id: '/dashboards/engenharia'
      path: '/engenharia'
      fullPath: '/dashboards/engenharia'
      preLoaderRoute: typeof DashboardsEngenhariaRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/comercial': {
      id: '/dashboards/comercial'
      path: '/comercial'
      fullPath: '/dashboards/comercial'
      preLoaderRoute: typeof DashboardsComercialRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/dashboards/aprovacoes': {
      id: '/dashboards/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/dashboards/aprovacoes'
      preLoaderRoute: typeof DashboardsAprovacoesRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/analytics/posvenda': {
      id: '/analytics/posvenda'
      path: '/posvenda'
      fullPath: '/analytics/posvenda'
      preLoaderRoute: typeof AnalyticsPosvendaRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/financiamentos': {
      id: '/analytics/financiamentos'
      path: '/financiamentos'
      fullPath: '/analytics/financiamentos'
      preLoaderRoute: typeof AnalyticsFinanciamentosRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/financeiro': {
      id: '/analytics/financeiro'
      path: '/financeiro'
      fullPath: '/analytics/financeiro'
      preLoaderRoute: typeof AnalyticsFinanceiroRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/estoque': {
      id: '/analytics/estoque'
      path: '/estoque'
      fullPath: '/analytics/estoque'
      preLoaderRoute: typeof AnalyticsEstoqueRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/engenharia': {
      id: '/analytics/engenharia'
      path: '/engenharia'
      fullPath: '/analytics/engenharia'
      preLoaderRoute: typeof AnalyticsEngenhariaRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/comercial': {
      id: '/analytics/comercial'
      path: '/comercial'
      fullPath: '/analytics/comercial'
      preLoaderRoute: typeof AnalyticsComercialRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/aprovacoes': {
      id: '/analytics/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/analytics/aprovacoes'
      preLoaderRoute: typeof AnalyticsAprovacoesRouteImport
      parentRoute: typeof AnalyticsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsAprovacoesRoute: typeof AnalyticsAprovacoesRoute
  AnalyticsComercialRoute: typeof AnalyticsComercialRoute
  AnalyticsEngenhariaRoute: typeof AnalyticsEngenhariaRoute
  AnalyticsEstoqueRoute: typeof AnalyticsEstoqueRoute
  AnalyticsFinanceiroRoute: typeof AnalyticsFinanceiroRoute
  AnalyticsFinanciamentosRoute: typeof AnalyticsFinanciamentosRoute
  AnalyticsPosvendaRoute: typeof AnalyticsPosvendaRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsAprovacoesRoute: AnalyticsAprovacoesRoute,
  AnalyticsComercialRoute: AnalyticsComercialRoute,
  AnalyticsEngenhariaRoute: AnalyticsEngenhariaRoute,
  AnalyticsEstoqueRoute: AnalyticsEstoqueRoute,
  AnalyticsFinanceiroRoute: AnalyticsFinanceiroRoute,
  AnalyticsFinanciamentosRoute: AnalyticsFinanciamentosRoute,
  AnalyticsPosvendaRoute: AnalyticsPosvendaRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface DashboardsRouteChildren {
  DashboardsAprovacoesRoute: typeof DashboardsAprovacoesRoute
  DashboardsComercialRoute: typeof DashboardsComercialRoute
  DashboardsEngenhariaRoute: typeof DashboardsEngenhariaRoute
  DashboardsEstoqueRoute: typeof DashboardsEstoqueRoute
  DashboardsFinanceiroRoute: typeof DashboardsFinanceiroRoute
  DashboardsFinanciamentosRoute: typeof DashboardsFinanciamentosRoute
  DashboardsPosvendaRoute: typeof DashboardsPosvendaRoute
}

const DashboardsRouteChildren: DashboardsRouteChildren = {
  DashboardsAprovacoesRoute: DashboardsAprovacoesRoute,
  DashboardsComercialRoute: DashboardsComercialRoute,
  DashboardsEngenhariaRoute: DashboardsEngenhariaRoute,
  DashboardsEstoqueRoute: DashboardsEstoqueRoute,
  DashboardsFinanceiroRoute: DashboardsFinanceiroRoute,
  DashboardsFinanciamentosRoute: DashboardsFinanciamentosRoute,
  DashboardsPosvendaRoute: DashboardsPosvendaRoute,
}

const DashboardsRouteWithChildren = DashboardsRoute._addFileChildren(
  DashboardsRouteChildren,
)

interface PaineisRouteChildren {
  PaineisAprovacoesRoute: typeof PaineisAprovacoesRoute
  PaineisComercialRoute: typeof PaineisComercialRoute
  PaineisEngenhariaRoute: typeof PaineisEngenhariaRoute
  PaineisEstoqueRoute: typeof PaineisEstoqueRoute
  PaineisFinanceiroRoute: typeof PaineisFinanceiroRoute
  PaineisFinanciamentosRoute: typeof PaineisFinanciamentosRoute
  PaineisPosvendaRoute: typeof PaineisPosvendaRoute
}

const PaineisRouteChildren: PaineisRouteChildren = {
  PaineisAprovacoesRoute: PaineisAprovacoesRoute,
  PaineisComercialRoute: PaineisComercialRoute,
  PaineisEngenhariaRoute: PaineisEngenhariaRoute,
  PaineisEstoqueRoute: PaineisEstoqueRoute,
  PaineisFinanceiroRoute: PaineisFinanceiroRoute,
  PaineisFinanciamentosRoute: PaineisFinanciamentosRoute,
  PaineisPosvendaRoute: PaineisPosvendaRoute,
}

const PaineisRouteWithChildren =
  PaineisRoute._addFileChildren(PaineisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisesRoute: AnalisesRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AprovacoesRoute: AprovacoesRoute,
  CadastrarRoute: CadastrarRoute,
  CadastrosRoute: CadastrosRoute,
  ComercialRoute: ComercialRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  DashboardsRoute: DashboardsRouteWithChildren,
  EngenhariaRoute: EngenhariaRoute,
  EstoqueRoute: EstoqueRoute,
  EstoqueFundacaoRoute: EstoqueFundacaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  FinanceiroTitulosRoute: FinanceiroTitulosRoute,
  FinanciamentosRoute: FinanciamentosRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PaineisRoute: PaineisRouteWithChildren,
  PedidosVendaRoute: PedidosVendaRoute,
  PosvendaRoute: PosvendaRoute,
  PropostasRoute: PropostasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SolicitacoesMaterialRoute: SolicitacoesMaterialRoute,
  TarefasRoute: TarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
