CREATE INDEX IF NOT EXISTS idx_tf_status_vencimento ON public.titulos_financeiros (status, vencimento) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tf_cliente_status ON public.titulos_financeiros (cliente_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tf_centro ON public.titulos_financeiros (centro_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tf_conta ON public.titulos_financeiros (conta_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tf_tipo_status ON public.titulos_financeiros (tipo, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tf_created_at ON public.titulos_financeiros (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pf_status_vencimento ON public.parcelas_financeiras (status, vencimento);
CREATE INDEX IF NOT EXISTS idx_mf_titulo_created ON public.movimentacoes_financeiras (titulo_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mf_tipo_data ON public.movimentacoes_financeiras (tipo, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pv_cliente_status ON public.pedidos_venda (cliente_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pv_consultor_status ON public.pedidos_venda (consultor_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pv_created_at ON public.pedidos_venda (created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_propostas_status_created ON public.propostas (status, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_contratos_cliente_status ON public.contratos (cliente_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_contratos_created_at ON public.contratos (created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_obras_cliente_status ON public.obras (cliente_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_obras_consultor_status ON public.obras (consultor_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_obras_created_at ON public.obras (created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_em_produto_created ON public.estoque_movimentos (produto_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_em_tipo_created ON public.estoque_movimentos (tipo, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_em_created_at ON public.estoque_movimentos (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_er_obra_status ON public.estoque_reservas (obra_id, status);
CREATE INDEX IF NOT EXISTS idx_er_produto_status ON public.estoque_reservas (produto_id, status);
CREATE INDEX IF NOT EXISTS idx_wf_status_created ON public.workflow_aprovacoes (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wf_solicitante_status ON public.workflow_aprovacoes (solicitante_id, status);
CREATE INDEX IF NOT EXISTS idx_wf_tipo_status ON public.workflow_aprovacoes (tipo_operacao, status);
CREATE INDEX IF NOT EXISTS idx_oc_created_at ON public.ordens_compra (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entidade_id_created ON public.audit_log (entidade, entidade_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON public.audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_anexos_entidade_created ON public.anexos (entidade_tipo, entidade_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tarefas_status_due ON public.tarefas (status, due_date);
CREATE INDEX IF NOT EXISTS idx_ev_entidade_id_versao ON public.entidade_versoes (entidade, entidade_id, versao DESC);
CREATE INDEX IF NOT EXISTS idx_gin_contratos_dados ON public.contratos USING GIN (dados);
CREATE INDEX IF NOT EXISTS idx_gin_obras_dados ON public.obras USING GIN (dados);
CREATE INDEX IF NOT EXISTS idx_gin_pv_dados ON public.pedidos_venda USING GIN (dados);
CREATE INDEX IF NOT EXISTS idx_gin_propostas_dados ON public.propostas USING GIN (dados);
CREATE INDEX IF NOT EXISTS idx_gin_leads_dados ON public.leads USING GIN (dados);
CREATE INDEX IF NOT EXISTS idx_gin_wf_contexto ON public.workflow_aprovacoes USING GIN (contexto);
ANALYZE public.titulos_financeiros;
ANALYZE public.parcelas_financeiras;
ANALYZE public.movimentacoes_financeiras;
ANALYZE public.pedidos_venda;
ANALYZE public.propostas;
ANALYZE public.contratos;
ANALYZE public.obras;
ANALYZE public.estoque_movimentos;
ANALYZE public.estoque_reservas;
ANALYZE public.workflow_aprovacoes;
ANALYZE public.audit_log;
ANALYZE public.anexos;